apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locallib
  template:
    metadata:
      labels:
        app: locallib
    spec:
      containers:
        - name: locallib
          image: mdshihabuddin/django-locallib
          ports:
            - containerPort: 6080

